Update gradle.yml

diff --git a/.github/workflows/gradle.yml b/.github/workflows/gradle.yml
--- a/.github/workflows/gradle.yml
+++ b/.github/workflows/gradle.yml
@@ -104,14 +104,16 @@ jobs:
           # 현재 실행 중인 포트 확인
           CURRENT_PORT=""
           if sudo systemctl is-active --quiet my-spring-app-1; then
+              echo "8081 서비스 실행 중!"
               CURRENT_PORT=8081
           elif sudo systemctl is-active --quiet my-spring-app-2; then
+              echo "8082 서비스 실행 중!"
               CURRENT_PORT=8082
           else
               echo "ERROR: Both services are inactive! Defaulting to 8081."
               CURRENT_PORT=8081
           fi
-          echo "=== DEBUG: Current running port is: $CURRENT_PORT ==="
+          echo "=== DEBUG: Current running port is: \$CURRENT_PORT ==="
 
 
           # CURRENT_PORT=\$(sudo systemctl is-active my-spring-app-1 && echo "8081" || (sudo systemctl is-active my-spring-app-2 && echo "8082"))
@@ -162,27 +164,27 @@ jobs:
           done
           
           # DOWN 상태 처리
-          if [ -z "$SUCCESS" ]; then
-            echo "ERROR: New application failed to start on port \$NEW_PORT"
+          # if [ -z "$SUCCESS" ]; then
+          #   echo "ERROR: New application failed to start on port \$NEW_PORT"
             
-            # 롤백 로직 (이전 버전으로 트래픽 재전환)
-            # DOWN 상태 처리
-            if [ -z "$SUCCESS" ]; then
-              echo "ERROR: New application failed to start on port \$NEW_PORT"
+          #   # 롤백 로직 (이전 버전으로 트래픽 재전환)
+          #   # DOWN 상태 처리
+          #   if [ -z "$SUCCESS" ]; then
+          #     echo "ERROR: New application failed to start on port \$NEW_PORT"
               
-              # 롤백 로직 (이전 버전으로 트래픽 재전환)
-              echo "Rolling back to previous version running on port \$CURRENT_PORT..."
-              sudo sed -i "s|proxy_pass http://.*|proxy_pass http://127.0.0.1:\$CURRENT_PORT;|" /etc/nginx/nginx.conf
-              sudo nginx -s reload
+          #     # 롤백 로직 (이전 버전으로 트래픽 재전환)
+          #     echo "Rolling back to previous version running on port \$CURRENT_PORT..."
+          #     sudo sed -i "s|proxy_pass http://.*|proxy_pass http://127.0.0.1:\$CURRENT_PORT;|" /etc/nginx/nginx.conf
+          #     sudo nginx -s reload
   
-              echo "Stopping failed new application: \$NEW_SERVICE"
-              sudo systemctl stop \$NEW_SERVICE || true
+          #     echo "Stopping failed new application: \$NEW_SERVICE"
+          #     sudo systemctl stop \$NEW_SERVICE || true
   
-              echo "Deployment failed. Rolled back to previous version on port \$CURRENT_PORT."
-              exit 1  
-            fi
+          #     echo "Deployment failed. Rolled back to previous version on port \$CURRENT_PORT."
+          #     exit 1  
+          #   fi
 
-          fi
+          # fi
 
           # Nginx 업데이트 및 reload
           echo "New application port: \$NEW_PORT"
