Update gradle.yml

diff --git a/.github/workflows/gradle.yml b/.github/workflows/gradle.yml
--- a/.github/workflows/gradle.yml
+++ b/.github/workflows/gradle.yml
@@ -168,15 +168,22 @@ jobs:
             echo "ERROR: New application failed to start on port $NEW_PORT"
             
             # 롤백 로직 (이전 버전으로 트래픽 재전환)
-            echo "🔄 Rolling back to previous version..."
+            # DOWN 상태 처리
+          if [ -z "$SUCCESS" ]; then
+            echo "ERROR: New application failed to start on port $NEW_PORT"
+            
+            # 롤백 로직 (이전 버전으로 트래픽 재전환)
+            echo "Rolling back to previous version running on port $CURRENT_PORT..."
             sudo sed -i "s|proxy_pass http://.*|proxy_pass http://127.0.0.1:$CURRENT_PORT;|" /etc/nginx/nginx.conf
             sudo nginx -s reload
-          
-            echo "Stopping failed new application..."
-            sudo systemctl stop my-spring-app
-          
-            echo "Deployment failed. Rolled back to the previous version running on port $CURRENT_PORT."
-            exit 1
+
+            echo "Stopping failed new application: $NEW_SERVICE"
+            sudo systemctl stop $NEW_SERVICE || true
+
+            echo "Deployment failed. Rolled back to previous version on port $CURRENT_PORT."
+            exit 1  # GitHub Actions에서 실패로 감지하도록 exit 1 추가
+          fi
+
           fi
 
 
@@ -203,13 +210,13 @@ jobs:
       
 
       # 실패시 이전 버전으로 롤백 가능하도록 하는것 
-      - name: Rollback to Previous Version
-        if: failure()
-        run: |
-          ssh \
-            -o StrictHostKeyChecking=yes \
-            ${{ secrets.AWS_EC2_USER }}@${{ secrets.AWS_EC2_HOST }} << EOF
-            PREV_JAR_FILE=\$(ls -t /home/ec2-user/*.jar | head -n 2 | tail -n 1)
-            ln -sfn \$PREV_JAR_FILE /home/ec2-user/Aplusmarket-latest.jar
-            sudo systemctl restart my-spring-app
-          EOF
+      # - name: Rollback to Previous Version
+      #   if: failure()
+      #   run: |
+      #     ssh \
+      #       -o StrictHostKeyChecking=yes \
+      #       ${{ secrets.AWS_EC2_USER }}@${{ secrets.AWS_EC2_HOST }} << EOF
+      #       PREV_JAR_FILE=\$(ls -t /home/ec2-user/*.jar | head -n 2 | tail -n 1)
+      #       ln -sfn \$PREV_JAR_FILE /home/ec2-user/Aplusmarket-latest.jar
+      #       sudo systemctl restart my-spring-app
+      #     EOF
